# Generated by Django 5.0.6 on 2024-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_alter_wishlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_picture_link',
            field=models.TextField(blank=True),
        ),
    ]
