# Generated by Django 5.0.6 on 2024-05-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0006_user_bio_alter_item_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_picture_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_in_wishlist', to='wish.wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='wish.user'),
        ),
    ]
